apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2021-07-18T06:31:00Z"
  name: hello-job
spec:
  completions: 10
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - echo
        - Hello I am from job
        image: busybox
        name: hello-job
        resources: {}
      restartPolicy: Never
status: {}