apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-analytics
spec:
 volumes:
  - name: pv-analytics
    hostPath:
      path: /pv/data-analytics
  capacity:    
    storage: 100Mi  
  accessModes:    
  - ReadWriteMany
