apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: use-pv-gabid
  labels:
    run: use-pv
    name: use-pvspec-gabid
spec:
  containers:
    - image: nginx
      name: use-pv
      resources: {}
volumeMounts:
  - mounthPath: /data
name: pv1-claim
volumes:
  - name: pv1-claim
    persistentVolumeClaim:
      claimName: pv1-claim
dnsPolicy: ClusterFirst
status: {}
